// apps/mobile/app/(tabs)/recipes/create.tsx
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useRouter, type Href } from 'expo-router';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  KeyboardAvoidingView,
  Platform,
  Pressable,
  ScrollView,
  TextInput,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { RecipeForm, type RecipeFormValues } from '@/components/recipe/RecipeForm';
import { DialogModal, DialogPanel } from '@/components/ui/DialogModal';
import { Box } from '@/components/ui/box';
import { Button, ButtonSpinner, ButtonText } from '@/components/ui/button';
import { Heading } from '@/components/ui/heading';
import { Text } from '@/components/ui/text';
import { openPlans } from '@/lib/billing/openPlans';
import { getEntitlementFeatureFromError } from '@/lib/entitlements/entitlementErrors';
import { usePaywallStore } from '@/lib/entitlements/paywallStore';
import { useRecipeEntitlements } from '@/lib/entitlements/useRecipeEntitlements';
import { useCurrentUser, useEntitlements } from '@/lib/queries/profile';
import { useCreateRecipe, useImportRecipeFromUrl } from '@/lib/queries/recipes';
import type { CreateRecipePayload, ImportRecipeFromUrlPayload } from '@/types/recipe';

export default function CreateRecipeScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const userQuery = useCurrentUser();
  const familyGroupId = userQuery.data?.family_group_id;
  const entitlementsQuery = useEntitlements(familyGroupId);
  const recipeEntitlements = useRecipeEntitlements(entitlementsQuery.data);
  const createRecipeMutation = useCreateRecipe();
  const importRecipeMutation = useImportRecipeFromUrl();
  const openPaywall = usePaywallStore((state) => state.openPaywall);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [importError, setImportError] = useState<string | null>(null);
  const [creationMode, setCreationMode] = useState<'manual' | 'import' | null>(null);
  const [creationMethodVisible, setCreationMethodVisible] = useState(true);
  const [importUrl, setImportUrl] = useState('');
  const [importProgressStep, setImportProgressStep] = useState(0);

  useEffect(() => {
    if (!importRecipeMutation.isPending) {
      setImportProgressStep(0);
      return;
    }

    const fetchingTimeout = setTimeout(() => setImportProgressStep(1), 900);
    const creatingTimeout = setTimeout(() => setImportProgressStep(2), 1800);

    return () => {
      clearTimeout(fetchingTimeout);
      clearTimeout(creatingTimeout);
    };
  }, [importRecipeMutation.isPending]);

  const handleOpenPlans = () => {
    openPlans(router);
  };

  const handleCloseMethodDialog = () => {
    if (creationMode) {
      setCreationMethodVisible(false);
      return;
    }

    router.back();
  };

  const handleSelectCreationMode = (mode: 'manual' | 'import') => {
    setCreationMode(mode);
    setCreationMethodVisible(false);
    setSubmitError(null);
    setImportError(null);
  };

  const handleCreate = async (formData: RecipeFormValues) => {
    if (!familyGroupId) {
      return;
    }

    if (!recipeEntitlements.canCreateRecipe) {
      openPaywall('recipes');
      return;
    }

    setSubmitError(null);

    try {
      const recipe = await createRecipeMutation.mutateAsync({
        familyGroupId,
        payload: formData as CreateRecipePayload,
      });
      void entitlementsQuery.refetch();
      router.replace(`/(tabs)/recipes/${recipe.id}` as Href);
    } catch (error) {
      const entitlementFeature = getEntitlementFeatureFromError(error);
      if (entitlementFeature) {
        openPaywall(entitlementFeature);
        return;
      }

      setSubmitError(t('recipeForm.createFailed'));
    }
  };

  const handleImportRecipe = async () => {
    if (!familyGroupId || !importUrl.trim()) {
      return;
    }

    if (!recipeEntitlements.canCreateRecipe) {
      openPaywall('recipes');
      return;
    }

    setImportError(null);

    try {
      const recipe = await importRecipeMutation.mutateAsync({
        familyGroupId,
        payload: { url: importUrl.trim() } as ImportRecipeFromUrlPayload,
      });
      void entitlementsQuery.refetch();
      router.replace(`/(tabs)/recipes/${recipe.id}/edit` as Href);
    } catch (error) {
      const entitlementFeature = getEntitlementFeatureFromError(error);
      if (entitlementFeature) {
        openPaywall(entitlementFeature);
        return;
      }

      setImportError(error instanceof Error ? error.message : t('recipeImport.genericError'));
    }
  };

  const importProgressMessages = [
    t('recipeImport.progress.validating'),
    t('recipeImport.progress.fetching'),
    t('recipeImport.progress.creating'),
  ];
  const importInputClassName =
    'rounded-lg border border-white/10 bg-surface px-4 py-3 text-base text-ice';

  return (
    <Box className="flex-1 bg-base" style={{ paddingTop: insets.top }}>
      <KeyboardAvoidingView
        className="flex-1"
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <ScrollView
          className="flex-1"
          contentContainerClassName="px-4 pb-8"
          keyboardShouldPersistTaps="handled"
        >
          <Pressable
            accessibilityRole="button"
            className="mb-4 flex-row items-center gap-2 py-2"
            onPress={() => router.back()}
          >
            <FontAwesome name="chevron-left" size={14} color="#F1F5F9" />
            <Text className="text-ice">{t('common.back')}</Text>
          </Pressable>

          <Heading className="mb-4 text-ice" size="lg">
            {t('recipeForm.newRecipe')}
          </Heading>

          {!recipeEntitlements.canCreateRecipe ? (
            <Box
              className="mb-4 rounded-lg border border-warning/40 bg-warning/15 px-4 py-3"
              testID="recipe-create-limit-alert"
            >
              <Text className="text-sm text-ice">{t('recipesPage.limitReached')}</Text>
              <Text className="mt-2 text-sm text-ice/80">
                {recipeEntitlements.recipeLimitHelperText}
              </Text>
              {recipeEntitlements.billing?.isOwner ? (
                <Pressable
                  accessibilityRole="link"
                  className="mt-3 self-start rounded-lg bg-primary px-3 py-2"
                  onPress={handleOpenPlans}
                >
                  <Text className="text-sm font-medium text-ice">
                    {t('recipesPage.upgradeLink')}
                  </Text>
                </Pressable>
              ) : null}
            </Box>
          ) : (
            <>
              {creationMode ? (
                <Box className="mb-4">
                  <Button variant="outline" size="sm" onPress={() => setCreationMethodVisible(true)}>
                    <ButtonText>{t('recipeImport.changeMethod')}</ButtonText>
                  </Button>
                </Box>
              ) : null}

              {creationMode === 'import' ? (
                <Box className="rounded-2xl border border-white/10 bg-surface px-4 py-4">
                  <Heading className="text-ice" size="md">
                    {t('recipeImport.title')}
                  </Heading>
                  <Text className="mt-2 text-sm text-ice/70">
                    {t('recipeImport.description')}
                  </Text>

                  <Text className="mb-2 mt-4 text-sm font-semibold text-ice">
                    {t('recipeImport.urlLabel')}
                  </Text>
                  <TextInput
                    className={importInputClassName}
                    placeholder={t('recipeImport.urlPlaceholder')}
                    placeholderTextColor="rgba(241, 245, 249, 0.4)"
                    value={importUrl}
                    onChangeText={setImportUrl}
                    autoCapitalize="none"
                    autoCorrect={false}
                    keyboardType="url"
                    editable={!importRecipeMutation.isPending}
                    testID="recipe-import-url-input"
                  />

                  {importError ? (
                    <Box className="mt-4 rounded-lg bg-red-500/15 px-4 py-3" testID="recipe-import-error">
                      <Text className="text-sm text-red-400">{importError}</Text>
                    </Box>
                  ) : null}

                  {importRecipeMutation.isPending ? (
                    <Box
                      className="mt-4 rounded-lg bg-primary/15 px-4 py-3"
                      testID="recipe-import-loading"
                    >
                      <Text className="text-sm font-semibold text-ice">
                        {t('recipeImport.loadingTitle')}
                      </Text>
                      <Text className="mt-1 text-sm text-ice/80">
                        {importProgressMessages[importProgressStep]}
                      </Text>
                    </Box>
                  ) : null}

                  <Box className="mt-4 flex-row justify-end gap-2">
                    <Button
                      variant="ghost"
                      onPress={() => router.back()}
                      disabled={importRecipeMutation.isPending}
                    >
                      <ButtonText>{t('common.cancel')}</ButtonText>
                    </Button>
                    <Button
                      className="bg-primary"
                      onPress={handleImportRecipe}
                      disabled={!importUrl.trim() || importRecipeMutation.isPending}
                      testID="recipe-import-submit-button"
                    >
                      {importRecipeMutation.isPending ? <ButtonSpinner color="#F1F5F9" /> : null}
                      <ButtonText className="text-ice">{t('recipeImport.submit')}</ButtonText>
                    </Button>
                  </Box>
                </Box>
              ) : creationMode === 'manual' ? (
                <>
                  {submitError ? (
                    <Box className="mb-4 rounded-lg bg-red-500/15 px-4 py-3">
                      <Text className="text-sm text-red-400">{submitError}</Text>
                    </Box>
                  ) : null}
                  <RecipeForm
                    submitLabel={t('recipeForm.createRecipe')}
                    isLoading={createRecipeMutation.isPending}
                    onSubmit={handleCreate}
                    onCancel={() => router.back()}
                  />
                </>
              ) : null}
            </>
          )}
        </ScrollView>
      </KeyboardAvoidingView>

      <DialogModal visible={creationMethodVisible} onClose={handleCloseMethodDialog}>
        <DialogPanel>
          <Heading size="lg" className="mb-3 text-ice">
            {t('recipeImport.chooseMethodTitle')}
          </Heading>
          <Text className="mb-6 text-ice/80">{t('recipeImport.chooseMethodDescription')}</Text>
          <Box className="gap-3">
            <Pressable
              accessibilityRole="button"
              className="rounded-xl border border-white/10 bg-base px-4 py-4"
              onPress={() => handleSelectCreationMode('manual')}
              testID="recipe-create-method-manual"
            >
              <Text className="font-semibold text-ice">{t('recipeImport.manualOptionTitle')}</Text>
              <Text className="mt-1 text-sm text-ice/70">
                {t('recipeImport.manualOptionDescription')}
              </Text>
            </Pressable>
            <Pressable
              accessibilityRole="button"
              className="rounded-xl border border-white/10 bg-base px-4 py-4"
              onPress={() => handleSelectCreationMode('import')}
              testID="recipe-create-method-import"
            >
              <Text className="font-semibold text-ice">{t('recipeImport.importOptionTitle')}</Text>
              <Text className="mt-1 text-sm text-ice/70">
                {t('recipeImport.importOptionDescription')}
              </Text>
            </Pressable>
          </Box>
          <Box className="mt-6 flex-row justify-end">
            <Button variant="ghost" onPress={handleCloseMethodDialog}>
              <ButtonText>{t('common.cancel')}</ButtonText>
            </Button>
          </Box>
        </DialogPanel>
      </DialogModal>
    </Box>
  );
}

// frontend/pages/recipes/create.vue
<template>
  <div class="max-w-4xl mx-auto px-4">
    <div class="flex items-center gap-2 my-4">
      <button class="btn btn-ghost btn-sm" @click="router.push('/recipes')">
        <fa icon="chevron-left" />
        {{ $t('Back') }}
      </button>
    </div>

    <h1 class="text-2xl font-bold mb-4">{{ $t('New Recipe') }}</h1>

    <div
      v-if="!canCreateRecipe"
      class="alert alert-warning mb-4"
      role="alert"
      data-testid="recipe-create-limit-alert"
    >
      <div class="flex flex-col gap-2 w-full">
        <span>{{ $t('recipesPage.limitReached') }}</span>
        <NuxtLink class="btn btn-primary btn-sm w-fit" to="/plans">
          {{ $t('recipesPage.upgradeLink') }}
        </NuxtLink>
      </div>
    </div>

    <div v-else class="space-y-4">
      <button
        v-if="creationMode"
        class="btn btn-outline btn-sm"
        @click="handleOpenCreationOptions"
      >
        {{ $t('recipeImport.changeMethod') }}
      </button>

      <div v-if="creationMode === 'import'" class="card bg-base-200 border border-base-300">
        <div class="card-body gap-4">
          <div>
            <h2 class="card-title">{{ $t('recipeImport.title') }}</h2>
            <p class="text-sm text-base-content/70">{{ $t('recipeImport.description') }}</p>
          </div>

          <label class="form-control">
            <span class="label">
              <span class="label-text font-semibold">{{ $t('recipeImport.urlLabel') }}</span>
            </span>
            <input
              v-model="importUrl"
              type="url"
              class="input input-bordered w-full"
              data-testid="recipe-import-url-input"
              :placeholder="$t('recipeImport.urlPlaceholder')"
              :disabled="isImporting"
            />
          </label>

          <div v-if="importError" class="alert alert-error" data-testid="recipe-import-error">
            <span>{{ importError }}</span>
          </div>

          <div
            v-if="isImporting"
            class="alert alert-info items-start"
            data-testid="recipe-import-loading"
          >
            <span class="loading loading-spinner loading-sm mt-0.5"></span>
            <div>
              <div class="font-medium">{{ $t('recipeImport.loadingTitle') }}</div>
              <div class="text-sm">{{ importProgressMessage }}</div>
            </div>
          </div>

          <div class="flex justify-end gap-2">
            <button class="btn btn-ghost" :disabled="isImporting" @click="router.push('/recipes')">
              {{ $t('Cancel') }}
            </button>
            <button
              class="btn btn-primary"
              data-testid="recipe-import-submit-button"
              :disabled="!canSubmitImport || isImporting"
              @click="handleImportRecipe"
            >
              <span v-if="isImporting" class="loading loading-spinner loading-sm"></span>
              <span>{{ $t('recipeImport.submit') }}</span>
            </button>
          </div>
        </div>
      </div>

      <RecipeForm
        v-else-if="creationMode === 'manual'"
        :submitLabel="$t('Create Recipe')"
        :isLoading="recipeStore.loading"
        @submit="handleCreate"
        @cancel="router.push('/recipes')"
      />
    </div>

    <dialog
      ref="creationOptionsDialog"
      class="modal"
      data-testid="recipe-create-method-dialog"
      @close="handleDismissCreationOptions"
    >
      <div class="modal-box space-y-4">
        <h2 class="text-xl font-semibold">{{ $t('recipeImport.chooseMethodTitle') }}</h2>
        <p class="text-sm text-base-content/70">{{ $t('recipeImport.chooseMethodDescription') }}</p>

        <div class="grid gap-3">
          <button
            class="btn btn-outline justify-start h-auto py-4"
            data-testid="recipe-create-method-manual"
            @click="handleSelectCreationMode('manual')"
          >
            <div class="text-left">
              <div class="font-semibold">{{ $t('recipeImport.manualOptionTitle') }}</div>
              <div class="text-xs text-base-content/70">{{ $t('recipeImport.manualOptionDescription') }}</div>
            </div>
          </button>
          <button
            class="btn btn-outline justify-start h-auto py-4"
            data-testid="recipe-create-method-import"
            @click="handleSelectCreationMode('import')"
          >
            <div class="text-left">
              <div class="font-semibold">{{ $t('recipeImport.importOptionTitle') }}</div>
              <div class="text-xs text-base-content/70">{{ $t('recipeImport.importOptionDescription') }}</div>
            </div>
          </button>
        </div>

        <div class="modal-action">
          <form method="dialog">
            <button class="btn btn-ghost" @click="handleDismissCreationOptions">
              {{ $t('Cancel') }}
            </button>
          </form>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop">
        <button @click="handleDismissCreationOptions">close</button>
      </form>
    </dialog>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth'
});

import { useRecipeStore } from '~/stores/recipe';
import { useUserStore } from '~/stores/user';
import RecipeForm from '~/components/recipe/RecipeForm.vue';
import { extractEntitlementError, extractErrorMessage } from '~/utils/httpError';

const router = useRouter();
const recipeStore = useRecipeStore();
const userStore = useUserStore();
const { t } = useI18n();
const { track } = useAnalytics();
const { hasFeature, refreshEntitlements } = useEntitlements();
const { openPaywall } = usePaywall();

const canCreateRecipe = hasFeature('recipes');
const creationMode = ref<'manual' | 'import' | null>(null);
const creationOptionsDialog = ref<HTMLDialogElement | null>(null);
const importUrl = ref('');
const importError = ref('');
const isImporting = ref(false);
const importProgressStep = ref(0);
let importProgressTimeouts: ReturnType<typeof setTimeout>[] = [];

const importProgressKeys = [
  'recipeImport.progress.validating',
  'recipeImport.progress.fetching',
  'recipeImport.progress.creating',
] as const;

const importProgressMessage = computed(() => t(importProgressKeys[importProgressStep.value]));
const canSubmitImport = computed(() => importUrl.value.trim().length > 0);

const clearImportProgress = () => {
  importProgressTimeouts.forEach(clearTimeout);
  importProgressTimeouts = [];
};

const startImportProgress = () => {
  clearImportProgress();
  importProgressStep.value = 0;
  importProgressTimeouts = [
    setTimeout(() => {
      importProgressStep.value = 1;
    }, 900),
    setTimeout(() => {
      importProgressStep.value = 2;
    }, 1800),
  ];
};

const handleOpenCreationOptions = async () => {
  await nextTick();
  creationOptionsDialog.value?.showModal();
};

const handleSelectCreationMode = (mode: 'manual' | 'import') => {
  creationMode.value = mode;
  importError.value = '';
  creationOptionsDialog.value?.close();
};

const handleDismissCreationOptions = () => {
  if (!creationMode.value) {
    router.push('/recipes');
  }
};

const handleCreate = async (formData) => {
  if (!canCreateRecipe.value) {
    openPaywall('recipes');
    return;
  }

  try {
    const recipe = await recipeStore.createRecipe(formData);
    if (recipe) {
      track('recipe_created');
      router.push(`/recipes/${recipe.id}`);
    }
  } catch (error) {
    const entitlementError = extractEntitlementError(error);
    if (entitlementError?.feature === 'recipes') {
      openPaywall('recipes');
      return;
    }

    console.error('Error creating recipe:', error);
  }
};

const handleImportRecipe = async () => {
  if (!canCreateRecipe.value || !canSubmitImport.value) {
    return;
  }

  importError.value = '';
  isImporting.value = true;
  startImportProgress();

  try {
    const recipe = await recipeStore.importRecipeFromUrl({ url: importUrl.value.trim() });
    if (recipe) {
      track('recipe_imported');
      router.push(`/recipes/${recipe.id}/edit`);
    }
  } catch (error) {
    const entitlementError = extractEntitlementError(error);
    if (entitlementError?.feature === 'recipes') {
      openPaywall('recipes');
      return;
    }

    importError.value = extractErrorMessage(error) || t('recipeImport.genericError');
    console.error('Error importing recipe:', error);
  } finally {
    isImporting.value = false;
    clearImportProgress();
  }
};

onMounted(async () => {
  if (!userStore.user?.family_group_id) {
    await userStore.fetchUser();
  }

  await refreshEntitlements();
  await handleOpenCreationOptions();
});

onBeforeUnmount(() => {
  clearImportProgress();
});
</script>
