// apps/mobile/app/(tabs)/recipes/index.tsx
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useRouter, type Href } from 'expo-router';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  ActivityIndicator,
  Linking,
  Pressable,
  RefreshControl,
  ScrollView,
  TextInput,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { RecipeCard } from '@/components/recipe/RecipeCard';
import { Box } from '@/components/ui/box';
import { Button, ButtonText } from '@/components/ui/button';
import { Heading } from '@/components/ui/heading';
import { Text } from '@/components/ui/text';
import { env } from '@/constants/env';
import { usePaywallStore } from '@/lib/entitlements/paywallStore';
import { useRecipeEntitlements } from '@/lib/entitlements/useRecipeEntitlements';
import { useCurrentUser, useEntitlements } from '@/lib/queries/profile';
import { useFamilyRecipes } from '@/lib/queries/recipes';

export default function RecipesScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const userQuery = useCurrentUser();
  const familyGroupId = userQuery.data?.family_group_id;
  const entitlementsQuery = useEntitlements(familyGroupId);
  const recipesQuery = useFamilyRecipes(familyGroupId);
  const openPaywall = usePaywallStore((state) => state.openPaywall);
  const recipeEntitlements = useRecipeEntitlements(entitlementsQuery.data);
  const [searchQuery, setSearchQuery] = useState('');

  const allRecipes = recipesQuery.data ?? [];
  const filteredRecipes = useMemo(() => {
    const query = searchQuery.trim().toLowerCase();
    if (!query) {
      return allRecipes;
    }

    return allRecipes.filter((recipe) => recipe.name.toLowerCase().includes(query));
  }, [allRecipes, searchQuery]);

  const hasRecipeData = allRecipes.length > 0;
  const showSkeleton = recipesQuery.isLoading && !hasRecipeData;
  const showListLoading = recipesQuery.isFetching && hasRecipeData;

  const handleOpenPlans = () => {
    void Linking.openURL(`${env.webUrl}/plans`);
  };

  const handleCreateRecipe = () => {
    if (!recipeEntitlements.canCreateRecipe) {
      openPaywall('recipes');
      return;
    }

    router.push('/(tabs)/recipes/create' as Href);
  };

  const handleRecipePress = (recipeId: number) => {
    router.push(`/(tabs)/recipes/${recipeId}` as Href);
  };

  const handleRefresh = () => {
    void recipesQuery.refetch();
    void entitlementsQuery.refetch();
  };

  return (
    <Box className="flex-1 bg-base" style={{ paddingTop: insets.top }}>
      <ScrollView
        className="flex-1"
        contentContainerClassName="px-4 pb-8"
        keyboardShouldPersistTaps="handled"
        refreshControl={
          <RefreshControl
            refreshing={showListLoading}
            onRefresh={handleRefresh}
            tintColor="#6366F1"
          />
        }
      >
        <Heading className="my-4 text-center text-2xl text-ice" size="xl">
          {t('recipeForm.title')}
        </Heading>

        {recipeEntitlements.recipeUsageLabel ? (
          <Text
            className="mb-2 text-center text-sm text-ice/70"
            testID="recipes-usage-label"
          >
            {recipeEntitlements.recipeUsageLabel}
          </Text>
        ) : null}

        {!recipeEntitlements.canCreateRecipe ? (
          <Box
            className="mb-4 rounded-lg border border-warning/40 bg-warning/15 px-4 py-3"
            testID="recipes-limit-alert"
          >
            <Text className="text-sm text-ice">{t('recipesPage.limitReached')}</Text>
            <Text className="mt-2 text-sm text-ice/80">
              {recipeEntitlements.recipeLimitHelperText}
            </Text>
            {recipeEntitlements.billing?.isOwner ? (
              <Pressable
                accessibilityRole="link"
                className="mt-3 self-start rounded-lg bg-primary px-3 py-2"
                onPress={handleOpenPlans}
              >
                <Text className="text-sm font-medium text-ice">
                  {t('recipesPage.upgradeLink')}
                </Text>
              </Pressable>
            ) : null}
          </Box>
        ) : null}

        <View className="mb-4 flex-row items-center gap-2">
          <View className="relative min-w-0 flex-1">
            <FontAwesome
              name="search"
              size={14}
              color="rgba(241, 245, 249, 0.5)"
              style={{ position: 'absolute', left: 12, top: 14, zIndex: 1 }}
            />
            <TextInput
              className="rounded-lg border border-white/10 bg-surface px-10 py-3 text-base text-ice"
              placeholder={t('recipeForm.searchPlaceholder')}
              placeholderTextColor="rgba(241, 245, 249, 0.4)"
              value={searchQuery}
              onChangeText={setSearchQuery}
              testID="recipes-search-input"
            />
          </View>
          <Button
            size="sm"
            className={recipeEntitlements.canCreateRecipe ? 'bg-primary' : 'bg-primary/40'}
            disabled={!recipeEntitlements.canCreateRecipe}
            onPress={handleCreateRecipe}
            testID="recipes-new-button"
          >
            <ButtonText className="text-ice">{t('recipeForm.newRecipe')}</ButtonText>
          </Button>
        </View>

        {showSkeleton ? (
          <Box className="items-center py-8">
            <ActivityIndicator size="large" color="#6366F1" />
          </Box>
        ) : allRecipes.length === 0 ? (
          <Box className="items-center py-12">
            <FontAwesome name="book" size={48} color="rgba(241, 245, 249, 0.3)" />
            <Text className="mt-4 text-lg font-medium text-ice">
              {t('recipeForm.emptyTitle')}
            </Text>
            <Text className="mt-2 text-center text-ice/60">
              {t('recipeForm.emptyDescription')}
            </Text>
            <Button
              className={`mt-4 ${recipeEntitlements.canCreateRecipe ? 'bg-primary' : 'bg-primary/40'}`}
              disabled={!recipeEntitlements.canCreateRecipe}
              onPress={handleCreateRecipe}
            >
              <FontAwesome name="plus" size={14} color="#F1F5F9" />
              <ButtonText className="ml-2 text-ice">{t('recipeForm.newRecipe')}</ButtonText>
            </Button>
          </Box>
        ) : filteredRecipes.length === 0 ? (
          <Box className="items-center py-12">
            <Text className="text-lg font-medium text-ice">
              {t('recipeForm.noResultsTitle')}
            </Text>
            <Text className="mt-2 text-ice/60">{t('recipeForm.noResultsDescription')}</Text>
          </Box>
        ) : (
          <View className="gap-3">
            {filteredRecipes.map((recipe) => (
              <RecipeCard
                key={recipe.id}
                recipe={recipe}
                onPress={() => handleRecipePress(recipe.id)}
              />
            ))}
          </View>
        )}
      </ScrollView>
    </Box>
  );
}

// frontend/pages/recipes/index.vue
<template>
  <div class="max-w-4xl mx-auto px-4">
    <h1 class="text-2xl font-bold text-center m-4">{{ $t('Recipe Book') }}</h1>

    <div
      v-if="recipeUsageLabel"
      class="text-sm text-center text-base-content/70 mb-2"
      data-testid="recipes-usage-label"
    >
      {{ recipeUsageLabel }}
    </div>

    <div
      v-if="!canCreateRecipe"
      class="alert alert-warning mb-4"
      role="alert"
      data-testid="recipes-limit-alert"
    >
      <div class="flex flex-col gap-2 w-full">
        <span>{{ $t('recipesPage.limitReached') }}</span>
        <span class="text-sm">{{ recipeLimitHelperText }}</span>
        <NuxtLink
          v-if="billing.isOwner"
          class="btn btn-primary btn-sm w-fit"
          to="/plans"
        >
          {{ $t('recipesPage.upgradeLink') }}
        </NuxtLink>
      </div>
    </div>

    <div class="flex gap-2 mb-4">
      <div class="relative flex-1">
        <fa icon="magnifying-glass" class="absolute left-3 top-1/2 -translate-y-1/2 text-base-content/50" />
        <input
          type="text"
          class="input input-bordered w-full pl-10"
          data-testid="recipes-search-input"
          :placeholder="$t('Search recipes...')"
          v-model="searchQuery"
          @input="handleSearch"
        />
      </div>
      <button
        class="btn btn-primary"
        data-testid="recipes-new-button"
        :disabled="!canCreateRecipe"
        @click="handleCreateRecipe"
      >
        <fa icon="plus" />
        <span class="hidden sm:inline">{{ $t('New Recipe') }}</span>
      </button>
    </div>

    <div v-if="recipeStore.loading && recipes.length === 0" class="flex justify-center py-8">
      <span class="loading loading-spinner loading-lg"></span>
    </div>

    <div v-else-if="recipeStore.recipes.length === 0" class="text-center py-12">
      <fa icon="book-open" class="text-5xl text-base-content/30 mb-4" />
      <p class="text-lg font-medium">{{ $t('No recipes yet') }}</p>
      <p class="text-base-content/60 mb-4">{{ $t('Create your first recipe to get started!') }}</p>
      <button class="btn btn-primary" :disabled="!canCreateRecipe" @click="handleCreateRecipe">
        <fa icon="plus" class="mr-1" />
        {{ $t('New Recipe') }}
      </button>
    </div>

    <div v-else-if="recipes.length === 0" class="text-center py-12">
      <p class="text-lg font-medium">{{ $t('No recipes found') }}</p>
      <p class="text-base-content/60">{{ $t('Try a different search term') }}</p>
    </div>

    <div v-else class="grid gap-3">
      <RecipeCard
        v-for="recipe in recipes"
        :key="recipe.id"
        :recipe="recipe"
        @click="navigateTo(`/recipes/${recipe.id}`)"
      />
    </div>
  </div>
</template>

<script setup>
definePageMeta({
  middleware: 'auth'
});

import { useRecipeStore } from '~/stores/recipe';
import { useUserStore } from '~/stores/user';
import RecipeCard from '~/components/recipe/RecipeCard.vue';

const recipeStore = useRecipeStore();
const userStore = useUserStore();
const router = useRouter();
const { t } = useI18n();
const {
  hasFeature,
  entitlements,
  billing,
  refreshEntitlements,
} = useEntitlements();
const { openPaywall } = usePaywall();

const searchQuery = ref('');
const canCreateRecipe = hasFeature('recipes');

const recipeUsageLabel = computed(() => {
  const usage = entitlements.value?.usage.recipeCount ?? 0;
  const maxRecipes = entitlements.value?.limits.maxRecipes;

  if (maxRecipes === undefined) {
    return null;
  }

  if (!Number.isFinite(maxRecipes)) {
    return t('recipesPage.usageUnlimited', { count: usage });
  }

  return t('recipesPage.usageLabel', { count: usage, max: maxRecipes });
});

const recipeLimitHelperText = computed(() => {
  if (billing.value.isOwner) {
    return t('recipesPage.upgradeLink');
  }

  if (billing.value.ownerDisplayName) {
    return t('recipesPage.askOwnerToUpgrade', { name: billing.value.ownerDisplayName });
  }

  return t('recipesPage.askOwnerToUpgradeGeneric');
});

const handleCreateRecipe = () => {
  if (!canCreateRecipe.value) {
    openPaywall('recipes');
    return;
  }

  router.push('/recipes/create');
};

const recipes = computed(() => {
  if (!searchQuery.value) return recipeStore.recipes;
  const query = searchQuery.value.toLowerCase();
  return recipeStore.recipes.filter(recipe =>
    recipe.name.toLowerCase().includes(query)
  );
});

const handleSearch = () => {
  recipeStore.setSearchQuery(searchQuery.value);
};

const navigateTo = (path) => {
  router.push(path);
};

onMounted(async () => {
  try {
    if (!userStore.user?.family_group_id) {
      await userStore.fetchUser();
    }
    await refreshEntitlements();
    await recipeStore.fetchRecipes();
  } catch (error) {
    console.error('Error loading recipes:', error);
  }
});
</script>
