// apps/mobile/app/(tabs)/diary/index.tsx
import { useTranslation } from 'react-i18next';
import { ActivityIndicator, RefreshControl, ScrollView } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { DayFoodPlanCard } from '@/components/diary/DayFoodPlanCard';
import { DiarySkeleton } from '@/components/diary/DiarySkeleton';
import { SetMealModal } from '@/components/diary/SetMealModal';
import { WeekCalendarPicker } from '@/components/diary/WeekCalendarPicker';
import { Box } from '@/components/ui/box';
import { Button, ButtonText } from '@/components/ui/button';
import { Heading } from '@/components/ui/heading';
import { Text } from '@/components/ui/text';
import { getDateForDay, getDayName, isDayInPast } from '@/lib/diary/dateUtils';
import { useMealDiaryEditor } from '@/lib/diary/useMealDiaryEditor';
import { useMealDiaryWeek } from '@/lib/diary/useMealDiaryWeek';
import { buildWeekDayMeals, toMealSlot } from '@/lib/diary/weeklyMeals';
import { useCurrentUser } from '@/lib/queries/profile';
import type { MealType } from '@/types/mealDiary';

export default function DiaryScreen() {
  const { t, i18n } = useTranslation();
  const insets = useSafeAreaInsets();
  const userQuery = useCurrentUser();
  const diary = useMealDiaryWeek(userQuery.data?.family_group_id);
  const mealEditor = useMealDiaryEditor();
  const familyGroupId = userQuery.data?.family_group_id;

  const hasMealData = diary.weeklyMeals.length > 0;
  const showSkeleton = diary.loading && !hasMealData;
  const showWeekLoading = diary.isFetching && hasMealData;
  const weekMeals = buildWeekDayMeals(diary.weeklyMeals, diary.resolvedWeekKey);

  const handleRefresh = () => {
    void userQuery.refetch();
    void diary.refreshWeek();
  };

  const handleRetry = () => {
    void diary.refreshWeek();
  };

  const handleSetMeal = (mealType: MealType, dayOfWeek: number) => {
    mealEditor.openMealEditor(mealType, dayOfWeek, diary.weeklyMeals);
  };

  const handleSaveMeal = () => {
    void mealEditor.handleSave(familyGroupId, diary.resolvedWeekKey, diary.weeklyMeals);
  };

  const handleClearMeal = () => {
    void mealEditor.handleClear(familyGroupId, diary.resolvedWeekKey, diary.weeklyMeals);
  };

  return (
    <Box className="flex-1 bg-base">
      <ScrollView
        contentContainerClassName="pb-8"
        contentContainerStyle={{ paddingTop: insets.top + 24 }}
        refreshControl={
          <RefreshControl
            refreshing={diary.isFetching && !diary.loading}
            onRefresh={handleRefresh}
            tintColor="#6366F1"
          />
        }
      >
        <Heading size="2xl" className="text-ice mb-4 text-center" testID="diary-title">
          {t('diary.title')}
        </Heading>

        {diary.lastFetchError && !diary.loading ? (
          <Box
            className="mx-4 mb-4 flex-row items-center justify-between rounded-xl bg-red-500/15 px-4 py-3"
            testID="diary-load-error"
          >
            <Text className="text-red-400 flex-1 text-sm">{t('diary.loadFailed')}</Text>
            <Button
              size="sm"
              variant="outline"
              onPress={handleRetry}
              testID="diary-retry-button"
            >
              <ButtonText>{t('diary.retry')}</ButtonText>
            </Button>
          </Box>
        ) : null}

        {showSkeleton ? (
          <DiarySkeleton />
        ) : (
          <>
            <WeekCalendarPicker
              key={diary.resolvedWeekKey}
              initialWeekStartDate={diary.displayWeekStartDate}
              isCurrentWeek={diary.isCurrentWeek}
              canSelectWeek={() => true}
              onWeekChange={diary.setWeek}
              onGoToThisWeek={diary.goToCurrentWeek}
            />
            <Box className="relative">
              <Box className={showWeekLoading ? 'opacity-50' : ''}>
                {weekMeals.map((dayMeal) => (
                  <DayFoodPlanCard
                    key={`${diary.resolvedWeekKey}-${dayMeal.day_of_week}`}
                    day={getDayName(dayMeal.day_of_week, diary.resolvedWeekKey, i18n.language)}
                    date={getDateForDay(diary.resolvedWeekKey, dayMeal.day_of_week, i18n.language)}
                    breakfast={toMealSlot(dayMeal.breakfast, dayMeal.breakfast_recipe_id)}
                    lunch={toMealSlot(dayMeal.lunch, dayMeal.lunch_recipe_id)}
                    dinner={toMealSlot(dayMeal.dinner, dayMeal.dinner_recipe_id)}
                    isPastDay={isDayInPast(diary.resolvedWeekKey, dayMeal.day_of_week)}
                    onSetMeal={(mealType) => handleSetMeal(mealType, dayMeal.day_of_week)}
                  />
                ))}
              </Box>

              {showWeekLoading ? (
                <Box
                  className="absolute inset-0 items-center justify-center"
                  testID="diary-week-loading"
                >
                  <ActivityIndicator size="large" color="#6366F1" />
                </Box>
              ) : null}
            </Box>
          </>
        )}
      </ScrollView>

      <SetMealModal
        visible={mealEditor.isModalVisible}
        mealName={mealEditor.selectedMeal.name}
        recipeId={mealEditor.selectedMeal.recipeId}
        isLoading={mealEditor.isSaving}
        error={mealEditor.saveError}
        onMealNameChange={mealEditor.updateMealName}
        onSave={handleSaveMeal}
        onClear={handleClearMeal}
        onClose={mealEditor.closeMealEditor}
      />
    </Box>
  );
}

// frontend/pages/diary/index.vue
<template>
  <div class="max-w-4xl mx-auto">
    <PullToRefreshChrome :enabled="pullToRefreshEnabled" :on-refresh="refreshWeek" />
    <h1 class="text-2xl font-bold text-center m-4" data-testid="diary-title">{{ $t('Meal diary') }}</h1>

    <div
      v-if="lastFetchError && !loading"
      class="alert alert-error mx-4 mb-4"
      role="alert"
      data-testid="diary-load-error"
    >
      <span>{{ $t('Failed to load meal diary') }}</span>
      <button
        type="button"
        class="btn btn-sm btn-ghost"
        data-testid="diary-retry-button"
        @click="handleRetry"
      >
        {{ $t('Retry') }}
      </button>
    </div>

    <MealDiarySkeleton v-if="showSkeleton" />
    <div v-else class="relative">
      <WeekCalendarPicker
        :key="resolvedWeekKey"
        :initialWeekStartDate="displayWeekStartDate"
        :is-current-week="isCurrentWeek"
        @weekChange="handleWeekChange"
        @go-to-this-week="handleGoToThisWeek"
      />
      <div
        class="relative"
        :class="{ 'opacity-50 pointer-events-none': showWeekLoading }"
      >
        <DayFoodPlanCard
          v-for="dayMeal in mealDiaryStore.weeklyMeals"
          :key="`${resolvedWeekKey}-${dayMeal.day_of_week}`"
          :day="getDayName(dayMeal.day_of_week, dayMeal.week_start_date)"
          :date="getDateForDay(dayMeal.week_start_date, dayMeal.day_of_week)"
          :breakfast="{ name: dayMeal.breakfast, recipeId: dayMeal.breakfast_recipe_id }"
          :lunch="{ name: dayMeal.lunch, recipeId: dayMeal.lunch_recipe_id }"
          :dinner="{ name: dayMeal.dinner, recipeId: dayMeal.dinner_recipe_id }"
          :isPastDay="isDayInPast(dayMeal.week_start_date, dayMeal.day_of_week)"
          @setMeal="(mealType) => handleSetMeal(mealType, dayMeal.day_of_week)"
        />
      </div>
      <div
        v-if="showWeekLoading"
        class="absolute inset-0 flex items-center justify-center z-10"
        aria-busy="true"
        data-testid="diary-week-loading"
      >
        <span class="loading loading-spinner loading-lg text-primary" />
      </div>
    </div>

    <dialog id="set_meal_modal" class="modal" data-testid="set-meal-modal">
      <SetUpdateMealModal
        v-if="mealDiaryStore.selectedMeal.type !== null"
        :meal="mealDiaryStore.selectedMeal.name"
        :recipeId="mealDiaryStore.selectedMeal.recipeId"
        @update:meal="mealDiaryStore.updateSelectedMealName"
        @update:recipeId="mealDiaryStore.updateSelectedMealRecipeId"
        @saveMeal="handleSaveMeal"
      />
    </dialog>
  </div>
</template>

<script setup>
definePageMeta({
  middleware: 'auth'
});

import { useMealDiaryStore } from '~/stores/mealDiary';
import DayFoodPlanCard from '~/components/diary/DayFoodPlanCard.vue';
import SetUpdateMealModal from '~/components/diary/SetUpdateMealModal.vue';
import WeekCalendarPicker from '~/components/WeekCalendarPicker.vue';
import MealDiarySkeleton from '~/components/diary/MealDiarySkeleton.vue';
import PullToRefreshChrome from '~/components/PullToRefreshChrome.vue';
import { useDateUtils } from '~/composables/useDateUtils.ts';
import { usePullToRefreshEnabled } from '~/composables/usePullToRefreshEnabled';
import { useMealDiaryWeek } from '~/composables/useMealDiaryWeek';

const { pullToRefreshEnabled } = usePullToRefreshEnabled();
const mealDiaryStore = useMealDiaryStore();
const { getDayName, getDateForDay, isDayInPast } = useDateUtils();

const {
  resolvedWeekKey,
  displayWeekStartDate,
  loading,
  lastFetchError,
  setWeek,
  refreshWeek,
  isCurrentWeek,
  goToCurrentWeek,
} = useMealDiaryWeek();

const hasMealData = computed(() => mealDiaryStore.weeklyMeals?.length > 0);
const showSkeleton = computed(() => loading.value && !hasMealData.value);
const showWeekLoading = computed(() => loading.value && hasMealData.value);

const handleSetMeal = (mealType, dayOfWeek) => {
  mealDiaryStore.setSelectedMeal(mealType, dayOfWeek);
  set_meal_modal.showModal();
};

const handleSaveMeal = async () => {
  try {
    await mealDiaryStore.saveMeal();
    set_meal_modal.close();
  } catch (error) {
    console.error('Error saving meal:', error);
  }
};

const handleWeekChange = (weekStartDate) => {
  void setWeek(weekStartDate);
};

const handleGoToThisWeek = () => {
  void goToCurrentWeek();
};

const handleRetry = () => {
  void refreshWeek();
};
</script>
