// frontend/pages/recipes/[id]/index.vue
<template>
  <div class="max-w-4xl mx-auto px-4">
    <div class="flex items-center gap-2 my-4">
      <button class="btn btn-ghost btn-sm" @click="router.push('/recipes')">
        <fa icon="chevron-left" />
        {{ $t('Back') }}
      </button>
    </div>

    <div v-if="recipeStore.loading && !recipe" class="flex justify-center py-8">
      <span class="loading loading-spinner loading-lg"></span>
    </div>

    <div v-else-if="recipe" class="pb-8">
      <div class="flex justify-between items-start mb-4">
        <h1 class="text-2xl font-bold">{{ recipe.name }}</h1>
        <div class="flex gap-2">
          <button class="btn btn-outline btn-sm" data-testid="recipe-edit-button" @click="handleEdit">
            <fa icon="pencil" class="mr-1" />
            {{ $t('Edit Recipe') }}
          </button>
          <button class="btn btn-error btn-outline btn-sm" data-testid="recipe-delete-button" @click="handleShowDeleteConfirm">
            <fa icon="trash" />
          </button>
        </div>
      </div>

      <p v-if="recipe.description" class="text-base-content/70 mb-4">{{ recipe.description }}</p>

      <div v-if="recipe.portions" class="badge badge-primary mb-4">
        {{ recipe.portions }} {{ $t('portions') }}
      </div>

      <!-- Ingredients -->
      <div v-if="recipe.ingredients?.length" class="mb-6">
        <h2 class="text-lg font-semibold mb-3">{{ $t('Ingredients') }}</h2>
        <div class="card bg-base-200">
          <div class="card-body p-4">
            <ul class="space-y-2">
              <li v-for="ingredient in recipe.ingredients" :key="ingredient.id" class="flex items-center gap-2">
                <span class="w-2 h-2 rounded-full bg-primary flex-shrink-0"></span>
                <span>{{ ingredient.name }}</span>
                <span v-if="ingredient.quantity || ingredient.unit" class="text-base-content/50 text-sm">
                  — {{ ingredient.quantity }}{{ ingredient.unit ? ` ${ingredient.unit}` : '' }}
                </span>
              </li>
            </ul>
          </div>
        </div>
        <button
          class="btn btn-outline btn-primary btn-sm mt-3"
          data-testid="recipe-add-to-shopping-list-button"
          :disabled="!canAddToShoppingList"
          @click="handleOpenAddToShoppingListModal"
        >
          <fa icon="list" class="mr-1" />
          {{ $t('Add to Shopping List') }}
        </button>
        <p v-if="!canAddToShoppingList" class="text-sm text-base-content/60 mt-2" data-testid="recipe-shopping-list-premium-hint">
          {{ $t('recipeDetail.shoppingListPremium') }}
          <NuxtLink v-if="billing.isOwner" class="link link-primary ml-1" to="/plans">
            {{ $t('recipeDetail.shoppingListUpgrade') }}
          </NuxtLink>
        </p>
      </div>

      <!-- Instructions -->
      <div v-if="recipe.instructions" class="mb-6">
        <h2 class="text-lg font-semibold mb-3">{{ $t('Instructions') }}</h2>
        <div class="card bg-base-200">
          <div class="card-body p-4">
            <p class="whitespace-pre-wrap">{{ recipe.instructions }}</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Add to shopping list modal -->
    <RecipeAddToShoppingListModal
      ref="addToShoppingListModalRef"
      :ingredients="recipe?.ingredients ?? []"
      :is-submitting="isAddingToShoppingList"
      @confirm="handleConfirmAddToShoppingList"
    />

    <!-- Delete confirmation modal -->
    <dialog id="delete_recipe_modal" class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">{{ $t('Delete Recipe') }}</h3>
        <p class="py-4">{{ $t('Are you sure you want to delete this recipe? It will also be removed from any meal diary entries.') }}</p>
        <div class="modal-action">
          <form method="dialog">
            <button class="btn btn-ghost mr-2">{{ $t('Cancel') }}</button>
          </form>
          <button class="btn btn-error" data-testid="recipe-confirm-delete-button" @click="handleDelete" :disabled="recipeStore.loading">
            <span v-if="recipeStore.loading" class="loading loading-spinner loading-sm"></span>
            <span v-else>{{ $t('Delete') }}</span>
          </button>
        </div>
      </div>
    </dialog>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  middleware: 'auth'
});

import { useRecipeStore } from '~/stores/recipe';
import { useUserStore } from '~/stores/user';
import { useApi } from '~/composables/useApi';
import { useToast } from '~/composables/useToast';
import { extractEntitlementError } from '~/utils/httpError';
import { buildShoppingListItemsFromRecipe } from '~/utils/buildShoppingListItemsFromRecipe';
import type { RecipeIngredient } from '~/types/Recipe';

const route = useRoute();
const router = useRouter();
const recipeStore = useRecipeStore();
const userStore = useUserStore();
const { showError } = useToast();
const { track } = useAnalytics();
const { hasFeature, billing, refreshEntitlements } = useEntitlements();
const { openPaywall } = usePaywall();
const { t } = useI18n();

const addToShoppingListModalRef = ref<{ showModal: () => void; closeModal: () => void } | null>(null);
const isAddingToShoppingList = ref(false);

const recipe = computed(() => recipeStore.currentRecipe);
const canAddToShoppingList = hasFeature('recipe_to_shopping_list');

const getIngredientKey = (ingredient: RecipeIngredient, index: number): string => {
  return ingredient.id != null ? String(ingredient.id) : `index-${index}`;
};

const filterIngredientsBySelectedKeys = (
  ingredients: RecipeIngredient[],
  selectedKeys: string[]
): RecipeIngredient[] => {
  const selectedKeySet = new Set(selectedKeys);
  return ingredients.filter((ingredient, index) =>
    selectedKeySet.has(getIngredientKey(ingredient, index))
  );
};

const handleEdit = () => {
  router.push(`/recipes/${route.params.id}/edit`);
};

const handleShowDeleteConfirm = () => {
  const modal = document.getElementById('delete_recipe_modal');
  if (modal) modal.showModal();
};

const handleDelete = async () => {
  try {
    await recipeStore.deleteRecipe(parseInt(route.params.id));
    track('recipe_deleted');
    const modal = document.getElementById('delete_recipe_modal');
    if (modal) modal.close();
    router.push('/recipes');
  } catch (error) {
    console.error('Error deleting recipe:', error);
  }
};

const handleOpenAddToShoppingListModal = () => {
  if (!canAddToShoppingList.value) {
    openPaywall('recipe_to_shopping_list');
    return;
  }

  if (!recipe.value?.ingredients?.length || !userStore.user?.family_group_id) return;

  addToShoppingListModalRef.value?.showModal();
};

const handleConfirmAddToShoppingList = async (selectedKeys: string[]) => {
  if (!recipe.value?.ingredients?.length || !userStore.user?.family_group_id) return;

  const selectedIngredients = filterIngredientsBySelectedKeys(recipe.value.ingredients, selectedKeys);
  if (!selectedIngredients.length) return;

  isAddingToShoppingList.value = true;

  try {
    const { api } = useApi();
    const familyGroupId = userStore.user.family_group_id;
    const items = buildShoppingListItemsFromRecipe(selectedIngredients);

    await api(`/api/shopping-list/${familyGroupId}/items/bulk`, {
      method: 'POST',
      silent: true,
      body: {
        items
      }
    });

    track('recipe_added_to_shopping_list', { item_count: items.length });
    addToShoppingListModalRef.value?.closeModal();
    const { showSuccess } = useToast();
    showSuccess('Ingredients added to shopping list!');
  } catch (error) {
    const entitlementError = extractEntitlementError(error);
    if (entitlementError?.feature === 'recipe_to_shopping_list') {
      openPaywall('recipe_to_shopping_list');
      return;
    }

    console.error('Error adding ingredients to shopping list:', error);
    showError(t('recipeDetail.addToShoppingListFailed'));
  } finally {
    isAddingToShoppingList.value = false;
  }
};

onMounted(async () => {
  if (!userStore.user?.family_group_id) {
    await userStore.fetchUser();
  }
  await refreshEntitlements();
  await recipeStore.fetchRecipeById(parseInt(route.params.id));
  track('recipe_viewed');
});
</script>

// apps/mobile/app/(tabs)/recipes/[id]/index.tsx
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useLocalSearchParams, useRouter, type Href } from 'expo-router';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import {
  ActivityIndicator,
  Pressable,
  RefreshControl,
  ScrollView,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

import { AddRecipeToShoppingListModal } from '@/components/recipe/AddRecipeToShoppingListModal';
import { DeleteRecipeModal } from '@/components/recipe/DeleteRecipeModal';
import { Box } from '@/components/ui/box';
import { Button, ButtonText } from '@/components/ui/button';
import { Heading } from '@/components/ui/heading';
import { Text } from '@/components/ui/text';
import { openPlans } from '@/lib/billing/openPlans';
import { isNetworkError } from '@/lib/auth/httpError';
import { getEntitlementFeatureFromError } from '@/lib/entitlements/entitlementErrors';
import { usePaywallStore } from '@/lib/entitlements/paywallStore';
import { useRecipeEntitlements } from '@/lib/entitlements/useRecipeEntitlements';
import { buildShoppingListItemsFromRecipe, formatIngredientDisplayLine } from '@/lib/recipe/buildShoppingListItemsFromRecipe';
import { useCurrentUser, useEntitlements } from '@/lib/queries/profile';
import { useDeleteRecipe, useRecipe } from '@/lib/queries/recipes';
import { useBulkAddShoppingListItems } from '@/lib/queries/shoppingList';
import { isShoppingListOfflineQueuedError } from '@/lib/shopping-list/shoppingListOfflineError';
import type { RecipeIngredient } from '@/types/recipe';

function getIngredientKey(ingredient: RecipeIngredient, index: number): string {
  return ingredient.id != null ? String(ingredient.id) : `index-${index}`;
}

function filterIngredientsBySelectedKeys(
  ingredients: RecipeIngredient[],
  selectedKeys: string[]
): RecipeIngredient[] {
  const selectedKeySet = new Set(selectedKeys);
  return ingredients.filter((ingredient, index) =>
    selectedKeySet.has(getIngredientKey(ingredient, index))
  );
}

export default function RecipeDetailScreen() {
  const { t } = useTranslation();
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { id } = useLocalSearchParams<{ id: string }>();
  const recipeId = id ? Number.parseInt(id, 10) : undefined;
  const parsedRecipeId = Number.isFinite(recipeId) ? recipeId : undefined;
  const userQuery = useCurrentUser();
  const familyGroupId = userQuery.data?.family_group_id;
  const entitlementsQuery = useEntitlements(familyGroupId);
  const recipeEntitlements = useRecipeEntitlements(entitlementsQuery.data);
  const recipeQuery = useRecipe(parsedRecipeId);
  const deleteRecipeMutation = useDeleteRecipe();
  const bulkAddShoppingListItemsMutation = useBulkAddShoppingListItems();
  const openPaywall = usePaywallStore((state) => state.openPaywall);
  const [isDeleteModalVisible, setIsDeleteModalVisible] = useState(false);
  const [isAddToShoppingListModalVisible, setIsAddToShoppingListModalVisible] = useState(false);
  const [addToShoppingListMessage, setAddToShoppingListMessage] = useState<string | null>(null);
  const [deleteError, setDeleteError] = useState<string | null>(null);

  const recipe = recipeQuery.data;
  const isLoading = recipeQuery.isLoading && !recipe;
  const isRefreshing = recipeQuery.isFetching && !!recipe;

  const handleEdit = () => {
    if (!parsedRecipeId) {
      return;
    }
    router.push(`/(tabs)/recipes/${parsedRecipeId}/edit` as Href);
  };

  const handleOpenPlans = () => {
    openPlans(router);
  };

  const handleOpenAddToShoppingListModal = () => {
    if (!recipe?.ingredients?.length || !familyGroupId) {
      return;
    }

    if (!recipeEntitlements.canAddToShoppingList) {
      openPaywall('recipe_to_shopping_list');
      return;
    }

    setAddToShoppingListMessage(null);
    setIsAddToShoppingListModalVisible(true);
  };

  const handleConfirmAddToShoppingList = async (selectedKeys: string[]) => {
    if (!recipe?.ingredients?.length || !familyGroupId) {
      return;
    }

    const selectedIngredients = filterIngredientsBySelectedKeys(recipe.ingredients, selectedKeys);
    if (!selectedIngredients.length) {
      return;
    }

    setAddToShoppingListMessage(null);

    try {
      const items = buildShoppingListItemsFromRecipe(selectedIngredients);
      await bulkAddShoppingListItemsMutation.mutateAsync({ familyGroupId, items });
      setIsAddToShoppingListModalVisible(false);
      setAddToShoppingListMessage(t('recipeDetail.addedToShoppingList'));
    } catch (error) {
      if (isShoppingListOfflineQueuedError(error) || isNetworkError(error)) {
        setIsAddToShoppingListModalVisible(false);
        setAddToShoppingListMessage(t('recipeDetail.addedToShoppingList'));
        return;
      }

      const entitlementFeature = getEntitlementFeatureFromError(error);
      if (entitlementFeature) {
        openPaywall(entitlementFeature);
        return;
      }

      setAddToShoppingListMessage(t('recipeDetail.addToShoppingListFailed'));
    }
  };

  const handleDelete = async () => {
    if (!parsedRecipeId || !familyGroupId) {
      return;
    }

    try {
      await deleteRecipeMutation.mutateAsync({
        recipeId: parsedRecipeId,
        familyGroupId,
      });
      setIsDeleteModalVisible(false);
      router.replace('/(tabs)/recipes' as Href);
    } catch {
      setIsDeleteModalVisible(false);
      setDeleteError(t('recipeForm.deleteFailed'));
    }
  };

  return (
    <Box className="flex-1 bg-base" style={{ paddingTop: insets.top }}>
      <ScrollView
        className="flex-1"
        contentContainerClassName="px-4 pb-8"
        refreshControl={
          <RefreshControl
            refreshing={isRefreshing}
            onRefresh={() => {
              void recipeQuery.refetch();
              void entitlementsQuery.refetch();
            }}
            tintColor="#6366F1"
          />
        }
      >
        <View className="mb-4 flex-row items-center justify-between gap-2">
          <Pressable
            accessibilityRole="button"
            className="flex-row items-center gap-2 py-2"
            onPress={() => router.back()}
          >
            <FontAwesome name="chevron-left" size={14} color="#F1F5F9" />
            <Text className="text-ice">{t('common.back')}</Text>
          </Pressable>

          {recipe ? (
            <View className="flex-row gap-2">
              <Button
                size="sm"
                variant="outline"
                onPress={handleEdit}
                testID="recipe-edit-button"
                accessibilityLabel={t('recipeForm.editRecipe')}
              >
                <FontAwesome name="pencil" size={12} color="#F1F5F9" />
              </Button>
              <Button
                size="sm"
                variant="outline"
                className="border-red-400"
                onPress={() => setIsDeleteModalVisible(true)}
                testID="recipe-delete-button"
                accessibilityLabel={t('recipeForm.deleteRecipe')}
              >
                <FontAwesome name="trash" size={12} color="#F87171" />
              </Button>
            </View>
          ) : null}
        </View>

        {isLoading ? (
          <Box className="items-center py-8">
            <ActivityIndicator size="large" color="#6366F1" />
          </Box>
        ) : !recipe ? (
          <Box className="items-center py-8">
            <Text className="text-ice/70">
              {recipeQuery.isError ? t('recipeDetail.loadFailed') : t('recipeDetail.notFound')}
            </Text>
            {recipeQuery.isError ? (
              <Button className="mt-4 bg-primary" onPress={() => void recipeQuery.refetch()}>
                <ButtonText>{t('diary.retry')}</ButtonText>
              </Button>
            ) : null}
          </Box>
        ) : (
          <>
            {deleteError ? (
              <Box className="mb-4 rounded-lg bg-red-500/15 px-4 py-3" testID="recipe-delete-error">
                <Text className="text-sm text-red-400">{deleteError}</Text>
              </Box>
            ) : null}
            <Heading className="mb-4 text-2xl text-ice" size="xl">
              {recipe.name}
            </Heading>

            {recipe.description ? (
              <Text className="mb-4 text-ice/70">{recipe.description}</Text>
            ) : null}

            {recipe.portions ? (
              <View className="mb-4 self-start rounded-full bg-primary px-3 py-1">
                <Text className="text-sm text-ice">
                  {recipe.portions} {t('recipeForm.portionsLabel')}
                </Text>
              </View>
            ) : null}

            {recipe.ingredients && recipe.ingredients.length > 0 ? (
              <Box className="mb-6">
                <Heading className="mb-3 text-lg text-ice" size="md">
                  {t('recipeForm.ingredients')}
                </Heading>
                <Box className="rounded-xl border border-white/10 bg-surface p-4">
                  <View className="gap-3">
                    {recipe.ingredients.map((ingredient, index) => (
                      <View
                        key={ingredient.id ?? `${ingredient.name}-${index}`}
                        className="flex-row items-start gap-2"
                      >
                        <View className="mt-2 h-2 w-2 rounded-full bg-primary" />
                        <Text className="flex-1 text-ice">
                          {formatIngredientDisplayLine(ingredient)}
                        </Text>
                      </View>
                    ))}
                  </View>
                </Box>
                <Button
                  size="sm"
                  variant="outline"
                  className="mt-3 w-full border-primary"
                  onPress={handleOpenAddToShoppingListModal}
                  disabled={bulkAddShoppingListItemsMutation.isPending}
                  testID="recipe-add-to-shopping-list-button"
                >
                  {bulkAddShoppingListItemsMutation.isPending ? (
                    <ActivityIndicator size="small" color="#6366F1" />
                  ) : (
                    <FontAwesome name="list" size={12} color="#6366F1" />
                  )}
                  <ButtonText className="ml-2 text-primary">
                    {t('recipeDetail.addToShoppingList')}
                  </ButtonText>
                </Button>
                {!recipeEntitlements.canAddToShoppingList ? (
                  <Text
                    className="mt-2 text-sm text-ice/60"
                    testID="recipe-shopping-list-premium-hint"
                  >
                    {t('recipeDetail.shoppingListPremium')}
                    {recipeEntitlements.billing?.isOwner ? (
                      <Text className="text-primary" onPress={handleOpenPlans}>
                        {' '}
                        {t('recipeDetail.shoppingListUpgrade')}
                      </Text>
                    ) : null}
                  </Text>
                ) : null}
                {addToShoppingListMessage ? (
                  <Text
                    className={`mt-2 text-sm ${
                      addToShoppingListMessage === t('recipeDetail.addedToShoppingList')
                        ? 'text-green-400'
                        : 'text-red-400'
                    }`}
                  >
                    {addToShoppingListMessage}
                  </Text>
                ) : null}
              </Box>
            ) : null}

            {recipe.instructions ? (
              <Box className="mb-6">
                <Heading className="mb-3 text-lg text-ice" size="md">
                  {t('recipeForm.instructions')}
                </Heading>
                <Box className="rounded-xl border border-white/10 bg-surface p-4">
                  <Text className="text-ice leading-6">{recipe.instructions}</Text>
                </Box>
              </Box>
            ) : null}
          </>
        )}
      </ScrollView>

      <AddRecipeToShoppingListModal
        visible={isAddToShoppingListModalVisible}
        ingredients={recipe?.ingredients ?? []}
        isSubmitting={bulkAddShoppingListItemsMutation.isPending}
        onClose={() => setIsAddToShoppingListModalVisible(false)}
        onConfirm={(selectedKeys) => void handleConfirmAddToShoppingList(selectedKeys)}
      />

      <DeleteRecipeModal
        visible={isDeleteModalVisible}
        isDeleting={deleteRecipeMutation.isPending}
        onClose={() => setIsDeleteModalVisible(false)}
        onConfirm={() => void handleDelete()}
      />
    </Box>
  );
}
