// frontend/components/shopping-list/ShoppingListCategoryTabs.vue
<template>
  <div
    class="tabs tabs-box tabs-sm w-full overflow-x-auto flex-nowrap mb-3"
    role="tablist"
    data-testid="shopping-list-category-tabs"
  >
    <button
      v-for="tab in tabs"
      :key="tab"
      type="button"
      role="tab"
      class="tab shrink-0"
      :class="{ 'tab-active': modelValue === tab }"
      :data-testid="`shopping-list-tab-${tab}`"
      :aria-selected="modelValue === tab"
      @click="handleSelect(tab)"
    >
      <span>{{ tabLabel(tab) }}</span>
      <span
        v-if="counts[tab]"
        class="badge badge-sm badge-ghost ml-1"
        :data-testid="`shopping-list-tab-count-${tab}`"
      >
        {{ counts[tab] }}
      </span>
    </button>
  </div>
</template>

<script setup lang="ts">
import {
  SHOPPING_LIST_TABS,
  type ShoppingListTab,
} from '@meal-diary/shared';

const props = defineProps<{
  modelValue: ShoppingListTab;
  counts: Record<ShoppingListTab, number>;
}>();

const emit = defineEmits<{
  'update:modelValue': [tab: ShoppingListTab];
}>();

const { t } = useI18n();

const tabs = SHOPPING_LIST_TABS;

const tabLabel = (tab: ShoppingListTab): string => {
  switch (tab) {
    case 'all':
      return t('All');
    case 'meat':
      return t('Meat');
    case 'fruit_veg':
      return t('Fruit & Veg');
    case 'bakery':
      return t('Bakery');
    case 'canned':
      return t('Canned');
    case 'other':
      return t('Other');
    default:
      return tab;
  }
};

const handleSelect = (tab: ShoppingListTab) => {
  emit('update:modelValue', tab);
};
</script>

// apps/mobile/components/shopping-list/ShoppingListCategoryTabs.tsx
import {
  SHOPPING_LIST_TABS,
  type ShoppingListTab,
} from '@meal-diary/shared';
import { useTranslation } from 'react-i18next';
import { Pressable, ScrollView } from 'react-native';

import { Box } from '@/components/ui/box';
import { Text } from '@/components/ui/text';

interface ShoppingListCategoryTabsProps {
  value: ShoppingListTab;
  onChange: (tab: ShoppingListTab) => void;
  counts: Record<ShoppingListTab, number>;
}

function tabLabelKey(tab: ShoppingListTab): string {
  switch (tab) {
    case 'all':
      return 'shoppingList.all';
    case 'meat':
      return 'shoppingList.meat';
    case 'fruit_veg':
      return 'shoppingList.fruitVeg';
    case 'bakery':
      return 'shoppingList.bakery';
    case 'canned':
      return 'shoppingList.canned';
    case 'other':
      return 'shoppingList.other';
    default:
      return 'shoppingList.other';
  }
}

export function ShoppingListCategoryTabs({
  value,
  onChange,
  counts,
}: ShoppingListCategoryTabsProps) {
  const { t } = useTranslation();

  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      className="mb-3"
      contentContainerClassName="gap-2 px-0"
      testID="shopping-list-category-tabs"
    >
      {SHOPPING_LIST_TABS.map((tab) => {
        const isActive = value === tab;
        const count = counts[tab] ?? 0;

        return (
          <Pressable
            key={tab}
            accessibilityRole="tab"
            accessibilityState={{ selected: isActive }}
            className={`flex-row items-center rounded-full px-3 py-2 ${
              isActive ? 'bg-primary' : 'bg-ice/10'
            }`}
            onPress={() => onChange(tab)}
            testID={`shopping-list-tab-${tab}`}
          >
            <Text className={`text-sm ${isActive ? 'text-ice font-semibold' : 'text-ice/80'}`}>
              {t(tabLabelKey(tab))}
            </Text>
            {count > 0 ? (
              <Box
                className={`ml-1.5 min-w-5 items-center rounded-full px-1.5 ${
                  isActive ? 'bg-ice/20' : 'bg-ice/10'
                }`}
                testID={`shopping-list-tab-count-${tab}`}
              >
                <Text className={`text-xs ${isActive ? 'text-ice' : 'text-ice/70'}`}>{count}</Text>
              </Box>
            ) : null}
          </Pressable>
        );
      })}
    </ScrollView>
  );
}
