// frontend/app/components/recipe/RecipeCard.vue
<template>
  <div class="card bg-base-200 shadow-sm cursor-pointer hover:bg-base-300 transition-colors" :data-testid="`recipe-card-${recipe.id}`" @click="$emit('click')">
    <div class="card-body p-4">
      <div class="flex justify-between items-start">
        <div class="flex-1">
          <h3 class="card-title text-base">{{ recipe.name }}</h3>
          <p v-if="recipe.description" class="text-sm text-base-content/60 mt-1 line-clamp-2">
            {{ recipe.description }}
          </p>
        </div>
        <div class="flex gap-2 items-center text-sm text-base-content/50">
          <span v-if="recipe.portions" class="badge badge-ghost badge-sm">
            {{ recipe.portions }} {{ $t('portions') }}
          </span>
          <span v-if="recipe.ingredients?.length" class="badge badge-ghost badge-sm">
            {{ recipe.ingredients.length }} {{ recipe.ingredients.length === 1 ? $t('ingredient') : $t('ingredients') }}
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  recipe: {
    type: Object,
    required: true,
  },
});

defineEmits(['click']);
</script>

// apps/mobile/components/recipe/RecipeCard.tsx
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { useTranslation } from 'react-i18next';
import { Pressable, View } from 'react-native';

import { Text } from '@/components/ui/text';
import type { Recipe } from '@/types/recipe';

interface RecipeCardProps {
  recipe: Recipe;
  onPress: () => void;
}

export function RecipeCard({ recipe, onPress }: RecipeCardProps) {
  const { t } = useTranslation();
  const ingredientCount = recipe.ingredients?.length ?? 0;

  return (
    <Pressable
      accessibilityRole="button"
      className="rounded-xl border border-white/10 bg-surface px-4 py-4 active:bg-white/5"
      onPress={onPress}
      testID={`recipe-card-${recipe.id}`}
    >
      <View className="flex-row items-start justify-between gap-3">
        <View className="min-w-0 flex-1">
          <Text className="text-base font-semibold text-ice">{recipe.name}</Text>
          {recipe.description ? (
            <Text className="mt-1 text-sm text-ice/60" numberOfLines={2}>
              {recipe.description}
            </Text>
          ) : null}
        </View>

        <View className="flex-row flex-wrap items-center justify-end gap-2">
          {recipe.portions ? (
            <View className="rounded-full border border-white/10 bg-base px-2 py-1">
              <Text className="text-xs text-ice/70">
                {recipe.portions} {t('recipeForm.portionsLabel')}
              </Text>
            </View>
          ) : null}
          {ingredientCount > 0 ? (
            <View className="rounded-full border border-white/10 bg-base px-2 py-1">
              <Text className="text-xs text-ice/70">
                {ingredientCount}{' '}
                {ingredientCount === 1
                  ? t('recipeForm.ingredient')
                  : t('recipeForm.ingredientsCount')}
              </Text>
            </View>
          ) : null}
        </View>
      </View>
    </Pressable>
  );
}
